# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Update Corpus Data

on: 
  push:
  repository_dispatch:

jobs:
  build:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']

    steps:
    - uses: actions/checkout@v2
    - name: Build data
      run: |
        timedatectl set-timezone Asia/Taipei
        pip install -r requirements.txt
        unzip -P ${{ secrets.FORMCORP }} form-corp-data.json.zip
        python3 download_corpus_data.py
        python3 GlossProcessor.py
        python3 GenerateMetas.py
        python3 GenerateMetasCSV.py
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        enable_jekyll: false